// Keycode numbering: which number each keycode name has on the connected board.
//
// QMK renumbers keycodes between keycode versions (0.0.9 moved the steno mode keys
// and combined chords), and a number means nothing outside its own numbering. The
// keycode catalog in keygen.ts supplies names, labels and the composed ranges; the
// numbers of QMK's explicitly numbered keycodes come from QMK's own data for the
// version the board reports, generated by scripts/qmk-keycodes.py.

import { CODEMAP, KEYALIASES, KEYMAP } from './keygen';
import qmk_0_0_9 from './qmk-keycodes/0.0.9.json';

export interface QmkKeycodes {
    version: string;
    ranges: Record<string, string>;
    /** "0x751C" -> ["QK_STENO_MODE_BOLT", ...aliases] */
    keycodes: Record<string, string[]>;
}

export const KEYCODE_NUMBERINGS: Record<string, QmkKeycodes> = {
    '0.0.9': qmk_0_0_9,
};

export const LATEST_KEYCODE_VERSION = '0.0.9';

/** Svalboard QMK builds from before the board reported its numbering all used 0.0.9. */
export const UNREPORTED_KEYCODE_VERSION = '0.0.9';

/** Catalog names QMK has since renamed; these keycodes also moved in 0.0.9. */
const RENAMED: Record<string, string> = {
    QK_STENO_BOLT: 'QK_STENO_MODE_BOLT',
    QK_STENO_GEMINI: 'QK_STENO_MODE_GEMINI',
    QK_STENO_COMB: 'QK_STENO_S3',
    QK_STENO_COMB_MAX: 'QK_STENO_EU',
};

function qmkNameFor(name: string): string {
    if (name in RENAMED) return RENAMED[name];
    // The catalog names combined steno chords STN_*, QMK names them QK_STENO_*.
    if (name.startsWith('STN_')) return 'QK_STENO_' + name.slice(4);
    return name;
}

// The catalog as shipped, so a numbering can be applied over it more than once.
const baseCodes = new Map(Object.entries(KEYMAP).map(([name, entry]) => [name, entry.code]));
const baseCodemap: Record<number, string> = { ...(CODEMAP as Record<number, string>) };
let addedNames: string[] = [];
let addedAliases: string[] = [];
let active = '';

export function activeKeycodeVersion(): string {
    return active;
}

export function isKnownKeycodeVersion(version: string): boolean {
    return version in KEYCODE_NUMBERINGS;
}

/**
 * Number the keycode tables the way QMK keycode version `version` does. Returns
 * false, changing nothing, for a version Keybard has no numbering for. Call before
 * keyService.generateAllKeycodes(), which layers the board's custom keycodes on top.
 */
export function applyKeycodeNumbering(version: string): boolean {
    const spec = KEYCODE_NUMBERINGS[version];
    if (!spec) return false;

    // Back to the catalog as shipped.
    for (const name of addedNames) delete KEYMAP[name];
    for (const alias of addedAliases) delete KEYALIASES[alias];
    addedNames = [];
    addedAliases = [];
    for (const [name, code] of baseCodes) {
        if (KEYMAP[name]) KEYMAP[name].code = code;
    }
    for (const code of Object.keys(CODEMAP)) delete CODEMAP[Number(code)];
    Object.assign(CODEMAP, baseCodemap);

    const catalogNamesFor = new Map<string, string[]>();
    for (const name of baseCodes.keys()) {
        const qmkName = qmkNameFor(name);
        catalogNamesFor.set(qmkName, [...(catalogNamesFor.get(qmkName) ?? []), name]);
    }

    // Give every catalog name for a QMK keycode that keycode's number.
    const namesByCode = new Map<number, string[]>();
    for (const [hex, qmkNames] of Object.entries(spec.keycodes)) {
        const code = parseInt(hex, 16);
        const names = [...new Set(qmkNames.flatMap(name => [name, ...(catalogNamesFor.get(name) ?? [])]))]
            .filter(name => name in KEYMAP);
        if (!names.length) {
            // A keycode the catalog lacks: list it under its QMK name.
            const [key, ...aliases] = qmkNames;
            const label = aliases.reduce((shortest, alias) => alias.length < shortest.length ? alias : shortest, key);
            KEYMAP[key] = { code, qmkid: key, str: label, title: key };
            addedNames.push(key);
            names.push(key);
        }
        for (const name of names) KEYMAP[name].code = code;
        for (const alias of qmkNames) {
            if (!(alias in KEYMAP) && !(alias in KEYALIASES)) {
                KEYALIASES[alias] = names[0];
                addedAliases.push(alias);
            }
        }
        namesByCode.set(code, names);
    }

    // Name each number by a name that still has it: keep the catalog's label unless
    // that keycode moved, in which case prefer a name the catalog labels elsewhere.
    const labels = new Set(Object.values(baseCodemap));
    for (const [code, names] of namesByCode) {
        const current = baseCodemap[code];
        if (current && KEYMAP[current]?.code === code) continue;
        CODEMAP[code] = names.find(name => labels.has(name)) ?? names[0];
    }
    for (const [code, name] of Object.entries(baseCodemap)) {
        const number = Number(code);
        if (!namesByCode.has(number) && KEYMAP[name] && KEYMAP[name].code !== number) delete CODEMAP[number];
    }

    active = version;
    return true;
}

applyKeycodeNumbering(LATEST_KEYCODE_VERSION);
